---
Name: cloudinary
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - https://widget.cloudinary.com/v2.0/global/all.js
Level51\Cloudinary\Cloudinary:
  theme: 'white'
  use_signed: true
  show_remove: false
  image_type: 'private'
  use_custom_gravity: true
  root_folder: ''
